// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Krateo Support",
            "url": "https://krateo.io",
            "email": "contact@krateoplatformops.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/plugin/{organization}/{project}/variablegroups": {
            "post": {
                "description": "Retrieves all variable groups for a project from Azure DevOps.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VariableGroup"
                ],
                "summary": "List variable groups (plugin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project name or ID",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "api-version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "CR spec forwarded by RDC; used to patch the matching item",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/variablegroup.VariableGroupParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List response with normalised items",
                        "schema": {
                            "$ref": "#/definitions/variablegroup.VariableGroupListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/plugin/{organization}/{project}/variablegroups/{groupId}": {
            "post": {
                "description": "Retrieves a variable group by ID from Azure DevOps, then patches secret",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VariableGroup"
                ],
                "summary": "Get a variable group (plugin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project name or ID",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Variable group ID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "api-version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "CR spec forwarded by RDC; used to restore secret variable values",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/variablegroup.VariableGroupParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Variable group with normalised booleans and patched secrets",
                        "schema": {
                            "$ref": "#/definitions/variablegroup.VariableGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a variable group from Azure DevOps by calling the organisation-level",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VariableGroup"
                ],
                "summary": "Delete a variable group (plugin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID (used as projectIds query param for the ADO delete endpoint)",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Variable group ID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "api-version",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content – variable group deleted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "variablegroup.IdentityRef": {
            "type": "object",
            "properties": {
                "descriptor": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "uniqueName": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "variablegroup.ProjectReference": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "variablegroup.VariableGroup": {
            "type": "object",
            "properties": {
                "createdBy": {
                    "$ref": "#/definitions/variablegroup.IdentityRef"
                },
                "createdOn": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isShared": {
                    "type": "boolean"
                },
                "modifiedBy": {
                    "$ref": "#/definitions/variablegroup.IdentityRef"
                },
                "modifiedOn": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "providerData": {
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "type": "string"
                },
                "variableGroupProjectReferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/variablegroup.VariableGroupProjectReference"
                    }
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/variablegroup.VariableValue"
                    }
                }
            }
        },
        "variablegroup.VariableGroupListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "value": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/variablegroup.VariableGroup"
                    }
                }
            }
        },
        "variablegroup.VariableGroupParameters": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "providerData": {
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "type": "string"
                },
                "variableGroupProjectReferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/variablegroup.VariableGroupProjectReference"
                    }
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/variablegroup.VariableValue"
                    }
                }
            }
        },
        "variablegroup.VariableGroupProjectReference": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "projectReference": {
                    "$ref": "#/definitions/variablegroup.ProjectReference"
                }
            }
        },
        "variablegroup.VariableValue": {
            "type": "object",
            "properties": {
                "isReadOnly": {
                    "type": "boolean"
                },
                "isSecret": {
                    "type": "boolean"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Azure DevOps VariableGroup Plugin API for Krateo Operator Generator (KOG)",
	Description:      "Simple wrapper around Azure DevOps API to handle VariableGroup delete operation with projectIds extraction",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
