apiVersion: azuredevops.ogen.krateo.io/v1alpha1
kind: GraphGroup
metadata:
  name: test-graphgroup-with-aad-originid-00001
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  # Reference to the configuration CR
  configurationRef:
    name: my-graphgroup-config
    namespace: default

  # Azure DevOps organization name
  organization: krateo-kog

  # Materialize an AAD group using the Origin ID
  originId: ""
