apiVersion: azuredevops.ogen.krateo.io/v1alpha1
kind: GraphGroup
metadata:
  name: test-graphgroup-00001
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  # Reference to the configuration CR
  configurationRef:
    name: my-graphgroup-config
    namespace: default

  # Azure DevOps organization name
  organization: krateo-kog

  # VSTS group creation fields
  displayName: Test Group from KOG 00001
  description: Test group created via Krateo OASGen Provider
