apiVersion: azuredevops.ogen.krateo.io/v1alpha1
kind: EnvironmentConfiguration
metadata:
  name: my-environment-config
  namespace: default
spec:
  authentication:
    basic:
      usernameRef:                  # Any value can be used as username as official Azure DevOps OAS suggests (field not used), but the secret and key must be set.
        name: azuredevops-secret
        namespace: default
        key: token
      passwordRef:
        name: azuredevops-secret
        namespace: default
        key: token
  configuration:
    query:
      create:
        api-version: "7.2-preview.1"
      delete:
        api-version: "7.2-preview.1"
      findby:
        api-version: "7.2-preview.1"
        $top: 100 # Optional: limit number of results per page
      get:
        api-version: "7.2-preview.1"
        expands: "resourceReferences" # Optional: include resource references (none | resourceReferences)
      update:
        api-version: "7.2-preview.1"
