apiVersion: v2
name: azuredevops-provider-kog-pipelinepermission
description: A Helm chart for deploying the Azure DevOps KOG PipelinePermission.
type: application
version: 1.0.0
appVersion: 1.0.0

home: https://krateo.io
icon: "https://github.com/krateoplatformops/krateo/blob/main/docs/media/logo.svg"
keywords:
  - generator
sources:
  - https://github.com/krateoplatformops-blueprints/azuredevops-provider-kog/tree/main/azuredevops-provider-kog-pipelinepermission-blueprint
annotations:
  krateoSupportedVersion: ">= 2.5.1"
