apiVersion: azuredevops.ogen.krateo.io/v1alpha1
kind: User
metadata:
  name: user-3
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
    krateo.io/deletion-policy: "orphan"
spec:
  # required: reference to a Configuration CR in the cluster
  configurationRef:
    name: my-user-config
    namespace: default
  organization: krateo-kog

  # Use either mailAddress, principalName, or origin + originId to identify the user.

  principalName: "330474cf-ed6a-463a-8591-0f06b9e515c0" # "This should be the principal name or upn of the user in the source AD or AAD provider.
