// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Krateo Support",
            "url": "https://krateo.io",
            "email": "contact@krateoplatformops.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/{organization}/{projectId}/git/repositories": {
            "post": {
                "description": "Create a new GitRepository on Azure DevOps using the provided organization, project, and repository details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a new GitRepository on Azure DevOps",
                "operationId": "post-gitrepository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID or name",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version (e.g., 7.2-preview.2)",
                        "name": "api-version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Specify the source refs to use while creating a fork repo",
                        "name": "sourceRef",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Basic Auth header (Basic \u003cbase64-encoded-username:password\u003e)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "GitRepository creation request body (with additional fields handled by the plugin)",
                        "name": "gitrepositoryCreate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gitrepository.CreateRepositoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "GitRepository details",
                        "schema": {
                            "$ref": "#/definitions/gitrepository.CreateRepositoryResponse"
                        }
                    },
                    "202": {
                        "description": "GitRepository details (repo created but creation of branch deisgnated as default branch is pending, user must create it, then the gitrepository-controller will update the default branch later)",
                        "schema": {
                            "$ref": "#/definitions/gitrepository.CreateRepositoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        }
    },
    "definitions": {
        "gitrepository.AzureDevOpsTime": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "gitrepository.CreateRepositoryRequest": {
            "type": "object",
            "properties": {
                "defaultBranch": {
                    "type": "string"
                },
                "initialize": {
                    "description": "Indicates if the repository should be initialized with an initial commit",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentRepository": {
                    "$ref": "#/definitions/gitrepository.GitRepositoryRefMinimal"
                },
                "project": {
                    "$ref": "#/definitions/gitrepository.TeamProjectReferenceMinimal"
                }
            }
        },
        "gitrepository.CreateRepositoryResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/gitrepository.ReferenceLinks"
                },
                "creationDate": {
                    "$ref": "#/definitions/gitrepository.AzureDevOpsTime"
                },
                "defaultBranch": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDisabled": {
                    "type": "boolean"
                },
                "isFork": {
                    "type": "boolean"
                },
                "isInMaintenance": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentRepository": {
                    "$ref": "#/definitions/gitrepository.GitRepositoryRef"
                },
                "project": {
                    "$ref": "#/definitions/gitrepository.TeamProjectReference"
                },
                "remoteUrl": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "sshUrl": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "validRemoteUrls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "webUrl": {
                    "type": "string"
                }
            }
        },
        "gitrepository.GitRepositoryRef": {
            "type": "object",
            "properties": {
                "collection": {
                    "$ref": "#/definitions/gitrepository.TeamProjectCollectionReference"
                },
                "id": {
                    "type": "string"
                },
                "isFork": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "project": {
                    "$ref": "#/definitions/gitrepository.TeamProjectReference"
                },
                "remoteUrl": {
                    "type": "string"
                },
                "sshUrl": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "gitrepository.GitRepositoryRefMinimal": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "project": {
                    "$ref": "#/definitions/gitrepository.TeamProjectReferenceMinimal"
                }
            }
        },
        "gitrepository.ProjectState": {
            "type": "string",
            "enum": [
                "deleting",
                "new",
                "wellFormed",
                "createPending",
                "all",
                "unchanged",
                "deleted"
            ],
            "x-enum-varnames": [
                "ProjectStateDeleting",
                "ProjectStateNew",
                "ProjectStateWellFormed",
                "ProjectStateCreatePending",
                "ProjectStateAll",
                "ProjectStateUnchanged",
                "ProjectStateDeleted"
            ]
        },
        "gitrepository.ProjectVisibility": {
            "type": "string",
            "enum": [
                "private",
                "public"
            ],
            "x-enum-varnames": [
                "ProjectVisibilityPrivate",
                "ProjectVisibilityPublic"
            ]
        },
        "gitrepository.ReferenceLinks": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "gitrepository.TeamProjectCollectionReference": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "gitrepository.TeamProjectReference": {
            "type": "object",
            "properties": {
                "abbreviation": {
                    "type": "string"
                },
                "defaultTeamImageUrl": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastUpdateTime": {
                    "$ref": "#/definitions/gitrepository.AzureDevOpsTime"
                },
                "name": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "state": {
                    "$ref": "#/definitions/gitrepository.ProjectState"
                },
                "url": {
                    "type": "string"
                },
                "visibility": {
                    "$ref": "#/definitions/gitrepository.ProjectVisibility"
                }
            }
        },
        "gitrepository.TeamProjectReferenceMinimal": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Azure DevOps GitRepository Plugin API for Krateo Operator Generator (KOG)",
	Description:      "Simple wrapper around Azure DevOps API to provide consistency of API response for Krateo Operator Generator (KOG)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
