apiVersion: v2
name: azuredevops-provider-kog
description: A Helm chart for deploying Azure DevOps Provider KOG.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: CHART_VERSION

home: https://krateo.io
icon: "https://github.com/krateoplatformops/krateo/blob/main/docs/media/logo.svg"
keywords:
  - generator
sources:
  - https://github.com/krateoplatformops-blueprints/azuredevops-provider-kog
annotations:
  krateoSupportedVersion: ">= 2.7.0"

dependencies:
  - name: azuredevops-provider-kog-gitrepository # the name of the dependency chart
    version: AZUREDEVOPS_PROVIDER_KOG_GITREPOSITORY_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-gitrepository-blueprint.enabled

  - name: azuredevops-provider-kog-pipeline
    version: AZUREDEVOPS_PROVIDER_KOG_PIPELINE_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-pipeline-blueprint.enabled

  - name: azuredevops-provider-kog-pipelinepermission
    version: AZUREDEVOPS_PROVIDER_KOG_PIPELINEPERMISSION_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-pipelinepermission-blueprint.enabled

  - name: azuredevops-provider-kog-pullrequest
    version: AZUREDEVOPS_PROVIDER_KOG_PULLREQUEST_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-pullrequest-blueprint.enabled

  - name: azuredevops-provider-kog-policyconfiguration
    version: AZUREDEVOPS_PROVIDER_KOG_POLICYCONFIGURATION_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-policyconfiguration-blueprint.enabled

  - name: azuredevops-provider-kog-repositorypermission
    version: AZUREDEVOPS_PROVIDER_KOG_REPOSITORYPERMISSION_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-repositorypermission-blueprint.enabled

  - name: azuredevops-provider-kog-buildpermission
    version: AZUREDEVOPS_PROVIDER_KOG_BUILDPERMISSION_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-buildpermission-blueprint.enabled

  - name: azuredevops-provider-kog-team
    version: AZUREDEVOPS_PROVIDER_KOG_TEAM_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-team-blueprint.enabled

  - name: azuredevops-provider-kog-graphgroup
    version: AZUREDEVOPS_PROVIDER_KOG_GRAPHGROUP_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-graphgroup-blueprint.enabled

  - name: azuredevops-provider-kog-project
    version: AZUREDEVOPS_PROVIDER_KOG_PROJECT_BLUEPRINT_VERSION
    repository: https://marketplace.krateo.io
    condition: azuredevops-provider-kog-project-blueprint.enabled
