# @schema
# type: object
# description: Configuration for the BuildPermission Blueprint dependency.
# @schema
azuredevops-provider-kog-buildpermission-blueprint:
  # @schema
  # type: boolean
  # description: Enable the BuildPermission Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the Environment Blueprint dependency.
# @schema
azuredevops-provider-kog-environment-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Environment Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the GitRepository Blueprint dependency.
# @schema
azuredevops-provider-kog-gitrepository-blueprint:
  # @schema
  # type: boolean
  # description: Enable the GitRepository Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the GraphGroup Blueprint dependency.
# @schema
azuredevops-provider-kog-graphgroup-blueprint:
  # @schema
  # type: boolean
  # description: Enable the GraphGroup Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the Membership Blueprint dependency.
# @schema
azuredevops-provider-kog-membership-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Membership Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the Pipeline Blueprint dependency.
# @schema
azuredevops-provider-kog-pipeline-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Pipeline Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the PipelinePermission Blueprint dependency.
# @schema
azuredevops-provider-kog-pipelinepermission-blueprint:
  # @schema
  # type: boolean
  # description: Enable the PipelinePermission Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the PolicyConfiguration Blueprint dependency.
# @schema
azuredevops-provider-kog-policyconfiguration-blueprint:
  # @schema
  # type: boolean
  # description: Enable the PolicyConfiguration Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the Project Blueprint dependency.
# @schema
azuredevops-provider-kog-project-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Project Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the PullRequest Blueprint dependency.
# @schema
azuredevops-provider-kog-pullrequest-blueprint:
  # @schema
  # type: boolean
  # description: Enable the PullRequest Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the RepositoryPermission Blueprint dependency.
# @schema
azuredevops-provider-kog-repositorypermission-blueprint:
  # @schema
  # type: boolean
  # description: Enable the RepositoryPermission Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the Team Blueprint dependency.
# @schema
azuredevops-provider-kog-team-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Team Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the User Blueprint dependency.
# @schema
azuredevops-provider-kog-user-blueprint:
  # @schema
  # type: boolean
  # description: Enable the User Blueprint dependency.
  # default: true
  # @schema
  enabled: true
# @schema
# type: object
# description: Configuration for the VariableGroup Blueprint dependency.
# @schema
azuredevops-provider-kog-variablegroup-blueprint:
  # @schema
  # type: boolean
  # description: Enable the VariableGroup Blueprint dependency.
  # default: true
  # @schema
  enabled: true
