apiVersion: v2
name: azuredevops-provider-kog-graphgroup
description: A Helm chart for deploying the Azure DevOps KOG GraphGroup.
type: application
#version: GRAPHGROUP_CHART_VERSION
version: 1.0.0
#appVersion: GRAPHGROUP_APP_VERSION

home: https://krateo.io
icon: "https://github.com/krateoplatformops/krateo/blob/main/docs/media/logo.svg"
keywords:
  - generator
sources:
  - https://github.com/krateoplatformops-blueprints/azuredevops-provider-kog/tree/main/azuredevops-provider-kog-graphgroup-blueprint
annotations:
  krateoSupportedVersion: ">= 2.7.0"
