kind: RestDefinition
apiVersion: ogen.krateo.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-policyconfiguration
spec:
  oasPath: configmap://{{ .Release.Namespace }}/{{ .Release.Name }}-policyconfiguration/policyconfiguration.yaml
  resourceGroup: azuredevops.ogen.krateo.io
  resource:
    kind: PolicyConfiguration
    identifiers:
    - type.id
    - settings
    additionalStatusFields:
    - id
    - createdBy
    - createdDate
    - url
    - type.displayName
    excludedSpecFields:
    - configurationId
    - scope # Legacy, deprecated field. `scope` in `settings` should be used instead
    - continuationToken # This will be managed by the pagination section below
    verbsDescription:
    - action: findby
      method: GET
      path: /{organization}/{project}/_apis/policy/configurations
      identifiersMatchPolicy: AND # In order to match both type.id and settings identifiers when finding by
      pagination:
        type: continuationToken
        continuationToken:
          request:
            tokenIn: query
            tokenPath: "continuationToken"
          response:
            tokenIn: header
            tokenPath: "X-Ms-Continuationtoken"
    - action: get
      method: GET
      path: /{organization}/{project}/_apis/policy/configurations/{configurationId}
      requestFieldMapping:
        - inPath: configurationId
          inCustomResource: status.id
    - action: create
      method: POST
      path: /{organization}/{project}/_apis/policy/configurations
    - action: update
      method: PUT
      path: /{organization}/{project}/_apis/policy/configurations/{configurationId}
      requestFieldMapping:
        - inPath: configurationId
          inCustomResource: status.id
    - action: delete
      method: DELETE
      path: /{organization}/{project}/_apis/policy/configurations/{configurationId}
      requestFieldMapping:
        - inPath: configurationId
          inCustomResource: status.id
    configurationFields:
    # Common among all actions
    - fromOpenAPI:
        name: api-version
        in: query
      fromRestDefinition:
        actions: ["*"]
    # FindBy
    - fromOpenAPI:
        name: $top
        in: query
      fromRestDefinition:
        actions:
          - findby
    - fromOpenAPI:
        name: policyType
        in: query
      fromRestDefinition:
        actions:
          - findby
