apiVersion: v2
name: azuredevops-provider-kog-buildpermission
description: A Helm chart for deploying the Azure DevOps KOG Repository Permission.
type: application
version: 1.0.0
appVersion: "latest"

home: https://krateo.io
icon: "https://github.com/krateoplatformops/krateo/blob/main/docs/media/logo.svg"
keywords:
  - generator
sources:
  - https://github.com/krateoplatformops-blueprints/azuredevops-provider-kog/tree/main/azuredevops-provider-kog-buildpermission-blueprint
annotations:
  krateoSupportedVersion: ">= 2.6.0"
