// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Krateo Support",
            "url": "https://krateo.io",
            "email": "contact@krateoplatformops.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/plugin/{organization}/graph/groups": {
            "get": {
                "description": "Retrieve graph groups from Azure DevOps. When scopeDescriptor is not provided, filters out project-level groups to return only organization-level groups.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Graph Groups"
                ],
                "summary": "Get graph groups with optional filtering",
                "operationId": "get-graphgroups",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "organization",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Scope descriptor (e.g., project descriptor). When provided, returns all groups within that scope without filtering.",
                        "name": "scopeDescriptor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of subject types to filter by",
                        "name": "subjectTypes",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Continuation token for pagination",
                        "name": "continuationToken",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "API version (e.g., 7.2-preview.1)",
                        "name": "api-version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Basic Auth header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Retrieved graph groups with filtering metadata",
                        "schema": {
                            "$ref": "#/definitions/graphgroup.GraphGroupsResponse"
                        },
                        "headers": {
                            "X-MS-ContinuationToken": {
                                "type": "string",
                                "description": "Continuation token for pagination (if more results available)"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "graphgroup.GraphGroup": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": true
                },
                "description": {
                    "type": "string"
                },
                "descriptor": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "isCrossProject": {
                    "type": "boolean"
                },
                "mailAddress": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "originId": {
                    "type": "string"
                },
                "principalName": {
                    "type": "string"
                },
                "subjectKind": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "graphgroup.GraphGroupsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Count after filtering (equals originalCount if no filtering)",
                    "type": "integer"
                },
                "numberOfFilteredOut": {
                    "description": "Number of groups filtered out (0 if no filtering)",
                    "type": "integer"
                },
                "originalCount": {
                    "description": "Original count from Azure DevOps API",
                    "type": "integer"
                },
                "value": {
                    "description": "Array of graph groups",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graphgroup.GraphGroup"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Azure DevOps GraphGroup Plugin API for Krateo Operator Generator (KOG)",
	Description:      "Proxy wrapper around Azure DevOps Graph Groups API that filters organization-level groups when scopeDescriptor is not provided",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
