kind: RestDefinition
apiVersion: ogen.krateo.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-team
spec:
  oasPath: configmap://{{ .Release.Namespace }}/{{ .Release.Name }}-team/team.yaml
  resourceGroup: azuredevops.ogen.krateo.io
  resource:
    kind: Team
    identifiers:
    - name # Within the same project the name of a team must be unique therefore we can use it as identifier
    additionalStatusFields:
    - id
    excludedSpecFields:
    - teamId
    - id # TODO: to be evaluated if needed
    - identity
    - identityUrl
    - projectName
    - url
    verbsDescription:
    - action: findby
      method: GET
      path: /{organization}/_apis/projects/{projectId}/teams
    - action: get
      method: GET
      path: /{organization}/_apis/projects/{projectId}/teams/{teamId}
      requestFieldMapping:
        - inPath: teamId
          inCustomResource: status.id
    - action: create
      method: POST
      path: /{organization}/_apis/projects/{projectId}/teams
    - action: update
      method: PATCH
      path: /{organization}/_apis/projects/{projectId}/teams/{teamId}
      requestFieldMapping:
        - inPath: teamId
          inCustomResource: status.id
    - action: delete
      method: DELETE
      path: /{organization}/_apis/projects/{projectId}/teams/{teamId}
      requestFieldMapping:
        - inPath: teamId
          inCustomResource: status.id
    configurationFields:
    - fromOpenAPI:
        name: api-version
        in: query
      fromRestDefinition:
        actions: ["*"] # Common among all actions
    - fromOpenAPI:
        name: $expandIdentity
        in: query
      fromRestDefinition:
        actions: ["findby", "get"]
    - fromOpenAPI:
        name: $mine
        in: query
      fromRestDefinition:
        actions: ["findby"]
    - fromOpenAPI:
        name: $skip
        in: query
      fromRestDefinition:
        actions: ["findby"]
    - fromOpenAPI:
        name: $top
        in: query
      fromRestDefinition:
        actions: ["findby"]
